version: '3.8'

services:
  # Servicio de base de datos PostgreSQL
  database:
    image: postgres:13
    container_name: licitometro-postgres
    environment:
      POSTGRES_DB: licitometro
      POSTGRES_USER: licitometro_admin
      POSTGRES_PASSWORD: ${DB_PASSWORD:-licitometro_secret}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U licitometro_admin -d licitometro"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - licitometro-network

  # Servicio de aplicación principal
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: licitometro-ml-platform
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://licitometro_admin:${DB_PASSWORD:-licitometro_secret}@database:5432/licitometro
      - PORT=3000
      - LOG_LEVEL=info
    ports:
      - "3000:3000"
    depends_on:
      - database
      - redis
    networks:
      - licitometro-network

  # Servicio de caché y gestión de colas
  redis:
    image: redis:6.2-alpine
    container_name: licitometro-redis
    ports:
      - "6379:6379"
    networks:
      - licitometro-network

  # Servicio de monitoreo de logs
  logs:
    image: grafana/loki:2.4.0
    container_name: licitometro-logs
    ports:
      - "3100:3100"
    networks:
      - licitometro-network

  # Servicio de monitoreo de métricas
  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: licitometro-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - licitometro-network

  # Servicio de visualización de métricas
  grafana:
    image: grafana/grafana:8.1.5
    container_name: licitometro-grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - licitometro-network

  # Servicio de machine learning
  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    container_name: licitometro-ml-service
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://licitometro_admin:${DB_PASSWORD:-licitometro_secret}@database:5432/licitometro
    depends_on:
      - database
      - redis
    networks:
      - licitometro-network

networks:
  licitometro-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  grafana-data:
